management:
    endpoints:
        web:
            exposure:
                include: '*' #Enabling actuator endpoint
# RabbitMQ Properties
spring:
    rabbitmq:
        addresses: amqps://xrjbysaw:ESAki5A7fkGit0EMD3q2N6Z7V_KCK69J@fox.rmq.cloudamqp.com/xrjbysaw
    boot.admin.client.url: http://localhost:5555 #Boot Admin configuration, Actuator Admin is running on port 1234
    datasource:
        hikari:
            connectionTimeout: 20000
            maximumPoolSize: 5
        password: lpras
        url: "jdbc:mysql://localhost:3306/mybooksearchdb"
        username: lpras
    jpa:
        show-sql: true
        hibernate.ddl-auto: update
        properties:
            hibernate:
                format_sql: true
    application:
        name: my-booksearch-ms

server:
    port: 8000
eureka:
    client:
        service-url:
            default-zone: http://localhost:8761/eureka
        healthcheck:
            enabled: true
            
hystrix:
    command:
        my-bookprice-ms:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 500000

logging:
    level:
        root: ERROR
        com.lpras: DEBUG
        de.codecentric: ERROR
    pattern:
        console: '%-5level [%thread]-${PID} %logger{36}  - %msg%n'
