eureka:
    client:
        fetch-registry: false
        register-with-eureka: false
server:
    port: 8761
spring:
    application:
        name: netflix-eureka-naming-server
logging:
  level:
    root: DEBUG
  file:
    path: './logs/${spring.application.name}'
    name: ${logging.file.path}/app.log
